export const FETCH_CHARITIES_SUCCESS = 'FETCH_CHARITIES_SUCCESS';
export const FETCH_CHARITIES_FAILURE = 'FETCH_CHARITIES_FAILURE';
export const FETCH_TOTAL_DONATE_SUCCESS = 'FETCH_TOTAL_DONATE_SUCCESS';
export const FETCH_TOTAL_DONATE_FAILURE = 'FETCH_TOTAL_DONATE_FAILURE';
export const DONATE_SUCCESS = 'DONATE_SUCCESS';
export const DONATE_FAILURE = 'DONATE_FAILURE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';