export const LOAD_CHARITIES_SUCCESS = 'LOAD_CHARITIES_SUCCESS';
export const LOAD_ALL_DONATE_SUCCESS = 'LOAD_ALL_DONATE_SUCCESS';
export const DONATE_SUCCESS = 'DONATE_SUCCESS';
export const UPDATE_TOTAL_DONATE = 'UPDATE_TOTAL_DONATE';